<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="images\users\AhmedAlmershady.jpg" />
    <Content Include="images\users\Angelina.jpg" />
    <Content Include="images\users\bob.jpg" />
    <Content Include="images\users\Brad.jpg" />
    <Content Include="images\users\celia.jpg" />
    <Content Include="images\users\fredy.jpg" />
    <Content Include="images\users\hector.jpg" />
    <Content Include="images\users\LedysBedoya.jpg" />
    <Content Include="images\users\liv.jpg" />
    <Content Include="images\users\otep.jpg" />
    <Content Include="images\users\otep.png" />
    <Content Include="images\users\ozzy.jpg" />
    <Content Include="images\users\ozzy.png" />
    <Content Include="images\users\selena.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.7.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderPlus.Shared\OrderPlus.Shared.csproj" />
  </ItemGroup>

  

</Project>
