<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
  </PropertyGroup>
  
  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\images\VendePuesLogo_transparent.png" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="wwwroot\images\photo_2022-07-08_00-32-53.jpg" />
  </ItemGroup>

  
  <ItemGroup>
    <PackageReference Include="DialogService" Version="0.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.8" />
    <PackageReference Include="MudBlazor" Version="6.19.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Stripe.net" Version="45.11.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Net.Http.Json" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>    
    <ProjectReference Include="..\OrderPlus.Shared\OrderPlus.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
  </ItemGroup>
    <ItemGroup>    
      <Content Update="wwwroot\images\question.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Update="Resources\Resource.ar.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Resource.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Resource.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>  

</Project>
